snc_redis:
    clients:

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%/0"
            logging: '%kernel.debug%'
        document:
            type: predis
            alias: document_cache
            dsn: "%env(REDIS_URL)%/1"
            logging: '%kernel.debug%'
            options:
                replication: false
        user_session:
            type: predis
            alias: user_session
            dsn: "%env(REDIS_URL)%/2"
            logging: '%kernel.debug%'
            options:
                connection_persistent: true
        monolog:
            type: predis
            alias: monolog
            dsn: "%env(REDIS_URL)%/4"
            logging: false
            options:
                connection_persistent: true
    session:
        client: user_session
        prefix: fos_
    monolog:
        client: monolog
        key: monolog
